server:
  port: 8765
spring:
  application:
    name: book-service
eureka:
  instance:
    hostname: bookservice
  client:
    service-url:
    #注册Eureka服务器中，如果有多个，追加逗号,http://slave2:8762/eureka/
      defaultZone: http://slave1:8761/eureka/
