#server:
#  port: 8765
spring:
  application:
    name: book-service
#  profiles: book01
  datasource:               #配置数据库连接
    url: jdbc:mysql://localhost:3306/myself_database?charset=utf8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

    tomcat:
      max-active: 20
      test-while-idle: true
      validation-query: select 1
      default-auto-commit: false
      min-idle: 15
      initial-size: 15

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql   #数据源类型需要添加
  jackson:
    serialization: true

eureka:
#  instance:                         我自己给自己挖了坑，排查了很久...
#    hostname: book-service          有spring.application.name ，就不要添加eureka.instance.hostname 不然zuul服务无法通过 path-serviceId进行代理跳转
  client:
    service-url:
    #注册Eureka服务器中，如果有多个，追加逗号,http://slave2:8762/eureka/
#      defaultZone: http://slave1:8761/eureka/
      defaultZone: http://localhost:8761/eureka/


