spring:
  application:
    name: my-zuul
eureka:
#  instance:
#    hostname: my-zuul        有spring.application.name ，就不要添加eureka.instance.hostname
  client:
    service-url:
      defaultZone: http://slave1:8761/eureka/
zuul:
  routes:
    test:
      url: http://localhost:8765
    book01:                       #这个名称随便写
      path: /book/**              #浏览器访问  http://localhost:9000/book/... 就会代理到相应的服务
      serviceId: book-service
    user:
      path: /user/**
      serviceId: user-service


#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 60000
#ribbon:
#  ReadTimeout: 60000
#  ConnectTimeout: 60000
